-- @author: 김서연
USE team05;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS medal_summary;
DROP TABLE IF EXISTS medals;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS disciplines;
DROP TABLE IF EXISTS olympics;
DROP TABLE IF EXISTS countries;

SET FOREIGN_KEY_CHECKS = 1;