-- @author: 김서연
USE team02;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS medal_summary;
DROP TABLE IF EXISTS results;       
DROP TABLE IF EXISTS athletes;     
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS sports;      
DROP TABLE IF EXISTS olympics;
DROP TABLE IF EXISTS countries;

SET FOREIGN_KEY_CHECKS = 1;